#!/usr/bin/env sh

# ------------------------------------------------------------
# Gradle start up script for POSIX generated by Gradle Wrapper
# Works in Termux and typical Linux shells
# ------------------------------------------------------------

# Resolve APP_HOME
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done
SAVED="`pwd`"
cd "`dirname "$PRG"`" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

# Locate Java
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

if ! command -v "$JAVACMD" >/dev/null 2>&1 ; then
  echo "ERROR: Java runtime could not be found. Please install Java 17+ and set JAVA_HOME if necessary." 1>&2
  exit 1
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

# Pass through
exec "$JAVACMD" \
  -Dorg.gradle.appname=gradlew \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"